language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "sgirardin-github"
    token:
      secure: "cdda61947d1e3a199b9933f7340f75a2ad9413f5"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'